### ISSUE TITLE
Implement Entry Page

### ISSUE THREAD

**Issue by sandovaldavid** [sandovaldavid/project1_wiki#1]
Create a view that responds to the route `/wiki/TITLE`, where `TITLE` is the title of an encyclopedia entry.
### Tasks:
  - [x] Use the appropriate function in `util.py` to retrieve the content of the entry.
  - [x] If the entry does not exist, display an error page indicating that the requested page was not found.
  - [x] If the entry exists, display a page that includes the content of the entry.
  - [x] Ensure the page title includes the name of the entry.
