### ISSUE TITLE
Implement Search Functionality

### ISSUE THREAD

**Issue by sandovaldavid** [sandovaldavid/project1_wiki#3]
Allow users to search for encyclopedia entries using the search box in the sidebar.
### Tasks:
  - [x] Redirect the user to the entry’s page if the query matches the name of an encyclopedia entry.
  - [x] If the query does not exactly match an entry name, display a search results page listing all entries that contain the query as a substring.
  - [x] Ensure that clicking on any entry name in the search results takes the user to the corresponding entry page.
