### ISSUE TITLE
Implement Edit Page

### ISSUE THREAD

**Issue by sandovaldavid** [sandovaldavid/project1_wiki#5]
Allow users to edit the content of existing entries.
### Tasks:
  - [x] On each entry page, add a link to edit the content of the entry.
  - [x] Create an edit page that pre-populates a textarea with the existing Markdown content of the entry.
  - [x] Implement functionality to save the changes made.
  - [x] Redirect the user back to the entry’s page after saving the changes.
